### ISSUE TITLE
Security Issue: Info Leak

### ISSUE THREAD

**Issue by nafiez** [miniupnp/ngiflib#2]
There's an info leak found on git2tga.c in line 58-59. It seems it failed to freed the object of GifImgDestroy from memory, thus causing the info leak. Proof of info leak can be found below.

cc @RamadhanAmizudin

Valgrind output:
==110336== 
==110336== HEAP SUMMARY:
==110336==     in use at exit: 80 bytes in 1 blocks
==110336==   total heap usage: 3 allocs, 2 frees, 1,656 bytes allocated
==110336== 
==110336== Searching for pointers to 1 not-freed blocks
==110336== Checked 62,688 bytes
==110336== 
==110336== 80 bytes in 1 blocks are definitely lost in loss record 1 of 1
==110336==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==110336==    by 0x400D4D: main (gif2tga.c:60)
==110336== 
==110336== LEAK SUMMARY:
==110336==    definitely lost: 80 bytes in 1 blocks
==110336==    indirectly lost: 0 bytes in 0 blocks
==110336==      possibly lost: 0 bytes in 0 blocks
==110336==    still reachable: 0 bytes in 0 blocks
==110336==         suppressed: 0 bytes in 0 blocks
==110336== 
==110336== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==110336== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Looking at the code shows the GifImgDestroy failed to freed first_img from memory. When it clear out ngiflib_free(g), it still have remainder object on the memory thus leading to info leak.

Line 54 - 60:
void GifDestroy(struct ngiflib_gif * g) {
	if(g==NULL) return;
	if(g->palette) ngiflib_free(g->palette);
	if(g->frbuff.p8) ngiflib_free(g->frbuff.p8);
	GifImgDestroy(g->first_img);    **// object didn't free as it want**
	ngiflib_free(g);   **// failed to freed block memory**
}

**Comment by miniupnp** [comment]
I don't understand what is the issue with code in  git2tga.c in line 58-59 : https://github.com/miniupnp/ngiflib/blob/master/gif2tga.c#L58

valgrind doesn't find any leak on my machine.
Also please explain why GifImgDestroy() and nfiglib_free() are failing for you...

**Comment by nafiez** [comment]
In our environment, we do found it valid issue, even after rebooting the machine to clear some memory cache. However the leak issue seems to be inconsistent where it won't be easily triggered from our side. 

Our observation, GifImgDestroy() object didn't clear properly thus when ngiflib_free() tries to freed the memory, it failed at least in our test environment.

**Comment by miniupnp** [comment]
please provide a correct test case to reproduce the issue
