### ISSUE TITLE
Potential memory leak issue regarding the 'animation' variable at line 154 in ngiflibSDL.c

### ISSUE THREAD

**Issue by zyy0721** [miniupnp/ngiflib#30]
Hello, 
  I may have discovered a potential memory leak issue. 
  At line 154 of the ngiflibSDL file, the 'animation' variable is allocated using ngiflib_malloc, but there is no corresponding deallocation for 'animation' throughout the program. This may pose a potential memory leak risk. Would it be possible to add a 'free' operation for the 'animation' variable before the main function returns in the SDLaffgif.c file?

**Comment by miniupnp** [comment]
the pointer is returned by the function `SDL_LoadAnimatedGif()`. It is up to the caller to free the memory.
