### ISSUE TITLE
buffer() (CWE-126)

### ISSUE THREAD

**Issue by teamwoot** [miniupnp/ngiflib#8]
Hi Team, 

We observed that https://github.com/miniupnp/ngiflib/blob/master/gif2tga.c#L109

i.e

`p = tganame + strlen(tganame);`

Does not handle strings that are not \0-terminated; if given one it may perform an over-read (it could cause a crash if unprotected)

Request team to have a look.

Regards
Team W00t

**Comment by miniupnp** [comment]
doesn't snprintf() guarantees to null terminate the string ?
